In [1]:
import pandas as pd

In [2]:
import numpy as np
import pickle

In [3]:
data=pd.read_csv("datajee.csv")

In [4]:
data.head()

Name  Daily Hour  Coaching Mode  Syllabus Covered  Maintain  Psychology  \
0    A           3              1                54         1           1   
1    B           4              1                30         1           1   
2    C           3              1                24         0           0   
3    D           2              0                20         0          -1   
4    E           5              0                45         1          -1   

   Probablity  
0           1  
1           0  
2           0  
3           0  
4           1

In [5]:
data.describe()

Daily Hour  Coaching Mode  Syllabus Covered   Maintain  Psychology  \
count   53.000000      53.000000         53.000000  53.000000   53.000000   
mean     6.905660       0.075472         56.188679   0.509434   -0.018868   
std      4.848728       0.805010         25.295223   0.504695    0.771875   
min      0.000000      -1.000000          2.000000   0.000000   -1.000000   
25%      3.000000      -1.000000         36.000000   0.000000   -1.000000   
50%      6.000000       0.000000         60.000000   1.000000    0.000000   
75%     10.000000       1.000000         78.000000   1.000000    1.000000   
max     18.000000       1.000000         98.000000   1.000000    1.000000   

       Probablity  
count   53.000000  
mean     0.641509  
std      0.484146  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      1.000000  
max      1.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Name              52 non-null     object
 1   Daily Hour        53 non-null     int64 
 2   Coaching Mode     53 non-null     int64 
 3   Syllabus Covered  53 non-null     int64 
 4   Maintain          53 non-null     int64 
 5   Psychology        53 non-null     int64 
 6   Probablity        53 non-null     int64 
dtypes: int64(6), object(1)
memory usage: 3.0+ KB


In [7]:
data.isnull().sum()

Name                1
Daily Hour          0
Coaching Mode       0
Syllabus Covered    0
Maintain            0
Psychology          0
Probablity          0
dtype: int64

In [8]:
prob=pd.crosstab(index=data['Probablity'],columns='counts',normalize=True)
prob

col_0         counts
Probablity          
0           0.358491
1           0.641509

In [9]:
salstat=pd.crosstab(index=data['Coaching Mode'],columns=data['Probablity'])
salstat

Probablity     0   1
Coaching Mode       
-1             4  11
 0             7  12
 1             8  11

In [10]:
correlation=data.corr()           #Not correlated
correlation

Daily Hour  Coaching Mode  Syllabus Covered  Maintain  \
Daily Hour          1.000000      -0.264190          0.827238 -0.105719   
Coaching Mode      -0.264190       1.000000         -0.297255 -0.049119   
Syllabus Covered    0.827238      -0.297255          1.000000  0.014922   
Maintain           -0.105719      -0.049119          0.014922  1.000000   
Psychology          0.143388       0.280878          0.036629  0.074513   
Probablity          0.444071      -0.126614          0.629037  0.053459   

                  Psychology  Probablity  
Daily Hour          0.143388    0.444071  
Coaching Mode       0.280878   -0.126614  
Syllabus Covered    0.036629    0.629037  
Maintain            0.074513    0.053459  
Psychology          1.000000    0.135933  
Probablity          0.135933    1.000000

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix


In [14]:
data=data.drop(columns='Name')

In [15]:
new_data=pd.get_dummies(data)         #particular column has many sub type then split iand use 0 &1 so we can use Logistic regression easily
new_data

Daily Hour  Coaching Mode  Syllabus Covered  Maintain  Psychology  \
0            3              1                54         1           1   
1            4              1                30         1           1   
2            3              1                24         0           0   
3            2              0                20         0          -1   
4            5              0                45         1          -1   
5            7             -1                67         0          -1   
6            6             -1                70         1           0   
7            2              1                19         0           1   
8           12              1                87         1           0   
9           13              0                80         1           0   
10          16              0                97         0           0   
11          16              0                90         0           0   
12          13             -1                89         1           0   
13          11              1                78         1          -1   
14           9              1                80         0           0   
15           8              1                89         1           1   
16           6             -1                60         1           0   
17           5             -1                50         1           0   
18           5              1                70         0           0   
19           4              0                50         1           0   
20           1              0                36         0           0   
21          13             -1                85         0           0   
22          12             -1                80         0           0   
23          17              0                98         0           1   
24          18              0                80         0           1   
25           1             -1                55         1           0   
26           6              1                45         1           1   
27          12              1                67         0           0   
28           8              1                74         0          -1   
29           0              1                 2         0           1   
30           4              0                10         1           1   
31           7              0                45         0          -1   
32           4              0                50         1          -1   
33          10             -1                65         1           0   
34           2              1                20         0          -1   
35          11             -1                56         0          -1   
36           5             -1                67         1          -1   
37           1             -1                35         0          -1   
38           9             -1                80         1          -1   
39           1              1                14         1           0   
40           3              1                50         1           1   
41           5              1                52         0           1   
42           7             -1                77         0          -1   
43           4              0                30         0           0   
44           1              0                23         0          -1   
45           6              0                57         0           1   
46           9              0                60         1           1   
47          10              0                75         1           1   
48          16             -1                79         1           0   
49           0              1                10         1          -1   
50           3              0                25         1           0   
51           8              0                67         0           1   
52           2              1                60         1          -1   

    Probablity  
0            1  
1            0  
2         

In [16]:
column_list=new_data.columns

In [17]:
features=list(set(column_list)-set(['Probablity']))
features

['Coaching Mode', 'Psychology', 'Syllabus Covered', 'Maintain', 'Daily Hour']

In [18]:
y=new_data['Probablity'].values                 #storing output variabe in y
print(y)

[1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1
 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 0]


In [19]:
x=new_data[features].values                 #storing output variabe in x
print(x)

[[ 1  1 54  1  3]
 [ 1  1 30  1  4]
 [ 1  0 24  0  3]
 [ 0 -1 20  0  2]
 [ 0 -1 45  1  5]
 [-1 -1 67  0  7]
 [-1  0 70  1  6]
 [ 1  1 19  0  2]
 [ 1  0 87  1 12]
 [ 0  0 80  1 13]
 [ 0  0 97  0 16]
 [ 0  0 90  0 16]
 [-1  0 89  1 13]
 [ 1 -1 78  1 11]
 [ 1  0 80  0  9]
 [ 1  1 89  1  8]
 [-1  0 60  1  6]
 [-1  0 50  1  5]
 [ 1  0 70  0  5]
 [ 0  0 50  1  4]
 [ 0  0 36  0  1]
 [-1  0 85  0 13]
 [-1  0 80  0 12]
 [ 0  1 98  0 17]
 [ 0  1 80  0 18]
 [-1  0 55  1  1]
 [ 1  1 45  1  6]
 [ 1  0 67  0 12]
 [ 1 -1 74  0  8]
 [ 1  1  2  0  0]
 [ 0  1 10  1  4]
 [ 0 -1 45  0  7]
 [ 0 -1 50  1  4]
 [-1  0 65  1 10]
 [ 1 -1 20  0  2]
 [-1 -1 56  0 11]
 [-1 -1 67  1  5]
 [-1 -1 35  0  1]
 [-1 -1 80  1  9]
 [ 1  0 14  1  1]
 [ 1  1 50  1  3]
 [ 1  1 52  0  5]
 [-1 -1 77  0  7]
 [ 0  0 30  0  4]
 [ 0 -1 23  0  1]
 [ 0  1 57  0  6]
 [ 0  1 60  1  9]
 [ 0  1 75  1 10]
 [-1  0 79  1 16]
 [ 1 -1 10  1  0]
 [ 0  0 25  1  3]
 [ 0  1 67  0  8]
 [ 1 -1 60  1  2]]


In [20]:
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.4,random_state=0) 

In [21]:
logistic=LogisticRegression()

In [22]:
logistic.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
prediction=logistic.predict(test_x)       #prediction from the test data 
prediction

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1],
      dtype=int64)

In [24]:
confusion_matrix=confusion_matrix(test_y, prediction)     #confusion matrix   
confusion_matrix

array([[ 7,  5],
       [ 0, 10]], dtype=int64)

In [25]:
accuracy_score=accuracy_score(test_y, prediction)        #calculating the accuracy
print(accuracy_score)                                    #This is the accuracy it can be mor accurate if we romove some more 
                                                         

0.7727272727272727


In [26]:
print("No of misclassified value :",(test_y!=prediction).sum())

No of misclassified value : 5


In [27]:
new_data

Daily Hour  Coaching Mode  Syllabus Covered  Maintain  Psychology  \
0            3              1                54         1           1   
1            4              1                30         1           1   
2            3              1                24         0           0   
3            2              0                20         0          -1   
4            5              0                45         1          -1   
5            7             -1                67         0          -1   
6            6             -1                70         1           0   
7            2              1                19         0           1   
8           12              1                87         1           0   
9           13              0                80         1           0   
10          16              0                97         0           0   
11          16              0                90         0           0   
12          13             -1                89         1           0   
13          11              1                78         1          -1   
14           9              1                80         0           0   
15           8              1                89         1           1   
16           6             -1                60         1           0   
17           5             -1                50         1           0   
18           5              1                70         0           0   
19           4              0                50         1           0   
20           1              0                36         0           0   
21          13             -1                85         0           0   
22          12             -1                80         0           0   
23          17              0                98         0           1   
24          18              0                80         0           1   
25           1             -1                55         1           0   
26           6              1                45         1           1   
27          12              1                67         0           0   
28           8              1                74         0          -1   
29           0              1                 2         0           1   
30           4              0                10         1           1   
31           7              0                45         0          -1   
32           4              0                50         1          -1   
33          10             -1                65         1           0   
34           2              1                20         0          -1   
35          11             -1                56         0          -1   
36           5             -1                67         1          -1   
37           1             -1                35         0          -1   
38           9             -1                80         1          -1   
39           1              1                14         1           0   
40           3              1                50         1           1   
41           5              1                52         0           1   
42           7             -1                77         0          -1   
43           4              0                30         0           0   
44           1              0                23         0          -1   
45           6              0                57         0           1   
46           9              0                60         1           1   
47          10              0                75         1           1   
48          16             -1                79         1           0   
49           0              1                10         1          -1   
50           3              0                25         1           0   
51           8              0                67         0           1   
52           2              1                60         1          -1   

    Probablity  
0            1  
1            0  
2         

In [39]:
inputfeature=[0,0,54,0,3]
prob=logistic.predict_proba([inputfeature])[0][1]
round(prob*100,2)

96.24

In [31]:
with open("jee.pkl","wb") as file:
    pickle.dump(logistic,file)

In [32]:
import sklearn
sklearn.__file__

'C:\\Users\\Asus\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\sklearn\\__init__.py'